# -*- coding: utf-8 -*-
"""disaster_Management(f).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWUuhWMhBXLscAHbdGDBIYwEbjIMSEP_
"""



# Install required libraries
!pip install pandas scikit-learn matplotlib seaborn -q

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# Upload your JSON file in Google Colab
from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Load JSON dataset
raw_data_bytes = uploaded[filename]

# Decode bytes to string and remove any leading/trailing whitespace
raw_data_string = raw_data_bytes.decode('utf-8').strip()

# Find the first valid JSON start character ('{' or '[')
start_idx = -1
for i, char in enumerate(raw_data_string):
    if char == '{' or char == '[':
        start_idx = i
        break

if start_idx == -1:
    raise ValueError("Could not find a valid JSON start character ('{' or '[') in the uploaded file content.")

# Find the last valid JSON end character ('}' or ']')
end_idx = -1
for i in range(len(raw_data_string) - 1, -1, -1):
    char = raw_data_string[i]
    if char == '}' or char == ']':
        end_idx = i
        break

if end_idx == -1 or end_idx < start_idx:
    raise ValueError("Could not find a valid JSON end character ('}' or ']') corresponding to the start in the uploaded file content.")

# Extract the most likely JSON substring
json_string_to_parse = raw_data_string[start_idx : end_idx + 1]

# Further clean the extracted JSON string if it starts with '{' or '['
# by removing any non-whitespace characters that are not a quote immediately after the opening character.
if json_string_to_parse.startswith('{'):
    # Remove leading whitespace and newlines after '{' until a non-space/non-newline character is encountered
    idx = 1 # Start checking after '{'
    while idx < len(json_string_to_parse) and json_string_to_parse[idx].isspace():
        idx += 1
    if idx > 1: # If whitespace was found after '{'
        json_string_to_parse = '{' + json_string_to_parse[idx:]
elif json_string_to_parse.startswith('['):
    # Remove leading whitespace and newlines after '[' until a non-space/non-newline character is encountered
    idx = 1 # Start checking after '['
    while idx < len(json_string_to_parse) and json_string_to_parse[idx].isspace():
        idx += 1
    if idx > 1: # If whitespace was found after '['
        json_string_to_parse = '[' + json_string_to_parse[idx:]

# Now, attempt to load this cleaned substring
try:
    data = json.loads(json_string_to_parse)
except json.JSONDecodeError as e:
    # If there's still a JSONDecodeError, provide more context
    raise ValueError(f"Failed to decode JSON from file '{filename}': {e}.\nAttempted to parse this string (first 200 chars):\n'{json_string_to_parse[:200]}'...") from e

# Create a dictionary for quick student information lookup
students = {
    student["student_id"]: student
    for student in data["students"]
}

# Extract performance data
records = []

for student in data["performance_tracker"]:

    student_id = student["student_id"]

    record = {
        "student_id": student_id,
        "name": students.get(student_id, {}).get("name", "Unknown"),
        "department": students.get(student_id, {}).get("department", "Unknown"),
        "overall_attendance": student["overall_attendance_percentage"],
        "overall_average": student["overall_average_score"]
    }

    # Semester-wise features
    semesters = student.get("semesters", [])

    for sem in semesters:
        sem_no = sem["semester"]

        record[f"sem{sem_no}_attendance"] = sem["attendance_percentage"]

        scores = []

        for subject in sem.get("subjects", []):
            if "total_score" in subject:
                scores.append(subject["total_score"])

        if scores:
            record[f"sem{sem_no}_average"] = np.mean(scores)

    records.append(record)

# Convert into DataFrame
df = pd.DataFrame(records)

print("Dataset:")
display(df.head())

# Select numerical features for anomaly detection
features = [
    "overall_attendance",
    "overall_average"
]

# Add semester features automatically
for column in df.columns:
    if "attendance" in column or "average" in column:
        if column not in features:
            features.append(column)

X = df[features].fillna(df[features].mean())

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Isolation Forest model
model = IsolationForest(
    contamination=0.10,
    random_state=42
)

# Predict anomalies
df["anomaly"] = model.fit_predict(X_scaled)

# Convert result into understandable labels
df["status"] = df["anomaly"].map({
    1: "Normal",
    -1: "Anomaly"
})

# Add 'needs_advisor_support' based on anomaly status
df['needs_advisor_support'] = df['status'] == 'Anomaly'

# Anomaly score
df["anomaly_score"] = model.decision_function(X_scaled)

# Define risk levels and advice
anomaly_scores_for_anomalies = df[df['status'] == 'Anomaly']['anomaly_score']

# If there are anomalies, calculate the median score to differentiate between MEDIUM and CRITICAL
if not anomaly_scores_for_anomalies.empty:
    median_anomaly_score = anomaly_scores_for_anomalies.median()
else:
    # Default to a value that ensures no 'CRITICAL' risk if no anomalies are detected
    median_anomaly_score = 0

def get_risk_level_and_advice(row):
    if row['status'] == 'Normal':
        return 'LOW RISK', 'Advisory logged to Student Profile'
    else:
        if row['anomaly_score'] < median_anomaly_score: # More anomalous (lower score)
            return 'CRITICAL RISK', 'Immediate escalation trigger'
        else: # Less anomalous (higher score, but still an anomaly)
            return 'MEDIUM RISK', 'Alert queued for Academic Advisor Mentorship'

df[['risk_level', 'advice']] = df.apply(get_risk_level_and_advice, axis=1, result_type='expand')

# Display results in JSON format
print("\n--- Anomaly Detection Results (JSON) ---")
results_df_json = df[
    [
        "student_id",
        "name",
        "department",
        "overall_attendance",
        "overall_average",
        "status",
        "needs_advisor_support",
        "anomaly_score",
        "risk_level", # Added new column
        "advice"      # Added new column
    ]
].sort_values("anomaly_score").to_json(orient="records", indent=2)
print(results_df_json)

# Display only anomalous students in JSON format
anomalies = df[df["status"] == "Anomaly"]

print("\n--- Detected Anomalies (JSON) ---")
anomalies_json = anomalies[
    [
        "student_id",
        "name",
        "department",
        "overall_attendance",
        "overall_average",
        "anomaly_score",
        "needs_advisor_support",
        "risk_level", # Added new column
        "advice"      # Added new column
    ]
].to_json(orient="records", indent=2)
print(anomalies_json)

# Plot attendance vs average score
plt.figure(figsize=(9, 6))

normal = df[df["status"] == "Normal"]
anomaly = df[df["status"] == "Anomaly"]

plt.scatter(
    normal["overall_attendance"],
    normal["overall_average"],
    label="Normal"
)

plt.scatter(
    anomaly["overall_attendance"],
    anomaly["overall_average"],
    label="Anomaly",
    marker="x",
    s=100
)

plt.xlabel("Overall Attendance (%)")
plt.ylabel("Overall Average Score")
plt.title("Student Anomaly Detection")
plt.legend()
plt.grid(True)
plt.show()

# Save results
df.to_csv("student_anomaly_results.csv", index=False)

print("Results saved as student_anomaly_results.csv")