# -*- coding: utf-8 -*-
"""disaster_management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCAKwFNefWR8aemBtYEFIU5C_jDit8b9

# Project Proposal: AI-Powered Student Support & Smart Campus Intelligence System

 ## Sub-Module: Academic Disaster Management & Early Warning System (ADM-EWS)

 ### 1\. Project Overview

 **Project Title:** AI-Powered Student Support & Smart Campus Intelligence System\
 **Sub-Module:** Academic Disaster Management & Early Warning Anomaly Detection Engine (ADM-EWS)\
 **Domain:** Artificial Intelligence, Deep Learning, Time-Series Anomaly Detection, Smart Campus\
 **Team Size:** 4 Members\
 **Development Platform:** Python, Google Colab, GitHub\
 **Proposed Deployment:** Cloud / Campus Server

---

 ## 2\. Abstract

 The **Academic Disaster Management & Early Warning System (ADM-EWS)** is an AI-based system designed to identify students who may be at risk of academic failure, attendance shortage, disengagement, or examination debarment.

 Traditional academic systems generally use simple threshold-based alerts. For example, a student may be notified only after their attendance falls below 75%. At that stage, it may be difficult for the student to recover the required attendance.

 ADM-EWS improves this process by analyzing **historical attendance, academic performance, assignment submissions, and other temporal academic indicators**. Using machine learning and deep learning techniques, the system detects unusual behavioral patterns and predicts future academic risk.

 The proposed system will use an **LSTM Autoencoder for anomaly detection** and a **GRU-based forecasting model for academic-risk prediction**. A risk assessment layer will classify students into different risk levels and generate alerts for appropriate intervention.

---

 # 3\. Problem Statement

 Current academic management systems are mostly reactive rather than predictive.

 For example:

 - A student may have 90% attendance initially but begin missing classes regularly.
- A student may show a continuous decline in internal examination marks.
- Assignment submissions may become increasingly delayed.
- A combination of poor attendance and declining academic performance may indicate future failure.
- Existing systems may identify these problems only after a predefined threshold has already been crossed.

 Therefore, there is a need for an intelligent system that can **identify abnormal academic behavior early and predict potential academic problems before they become critical**.

---

 # 4\. Objectives

 The major objectives of ADM-EWS are:

 1. To collect and preprocess student academic time-series data.
2. To identify abnormal changes in student academic behavior.
3. To predict future attendance and academic performance.
4. To estimate the probability of academic risk or examination debarment.
5. To classify students into Low, Medium, and Critical risk categories.
6. To generate structured alerts for faculty/advisors.
7. To provide an API that can integrate with other modules of the Smart Campus system.
8. To evaluate the proposed models using suitable machine-learning metrics.

---

 # 5\. Proposed System

 The system will process multiple academic indicators and convert them into time-series features.

 ### Input Data

 The system can use:

 - Attendance percentage
- Weekly attendance
- Subject-wise attendance
- Internal examination marks
- Assignment submission status
- Assignment submission delay
- LMS activity
- Number of consecutive absences
- Previous academic performance

 For the initial implementation, **synthetic or anonymized data** can be used if real student data is unavailable.

---

 # 6\. System Architecture

```
                 ┌─────────────────────────────┐
                 │       Academic Data          │
                 │                             │
                 │ Attendance | Marks | LMS    │
                 │ Assignments | Submissions   │
                 └──────────────┬──────────────┘
                                │
                                ▼
                 ┌─────────────────────────────┐
                 │     Data Preprocessing      │
                 │                             │
                 │ Cleaning | Normalization    │
                 │ Missing Values | Features   │
                 └──────────────┬──────────────┘
                                │
                                ▼
                 ┌─────────────────────────────┐
                 │    Time-Series Features     │
                 │                             │
                 │ Weekly Attendance           │
                 │ Mark Trends                 │
                 │ Submission Delay            │
                 │ Consecutive Absence         │
                 └──────────────┬──────────────┘
                                │
                    ┌───────────┴───────────┐
                    ▼                       ▼
          ┌───────────────────┐   ┌────────────────────┐
          │ LSTM Autoencoder  │   │   GRU Predictor    │
          │                   │   │                    │
          │ Anomaly Detection │   │ Future Risk       │
          └─────────┬─────────┘   └──────────┬─────────┘
                    │                        │
                    └───────────┬────────────┘
                                ▼
                 ┌─────────────────────────────┐
                 │       Risk Assessment       │
                 │                             │
                 │ LOW | MEDIUM | CRITICAL     │
                 └──────────────┬──────────────┘
                                │
                                ▼
                 ┌─────────────────────────────┐
                 │      Alert / Dashboard      │
                 │                             │
                 │ Faculty | Advisor | Chatbot │
                 └─────────────────────────────┘
```

---

 # 7\. Methodology

 ## 7.1 Data Collection

 The first stage involves collecting or generating student academic records.

 A sample dataset could contain:

 | Student | Week | Attendance | Internal Mark | Assignments | Delay |
| --- | --- | --- | --- | --- | --- |
| S001 | 1 | 92 | 78 | 3/3 | 0 |
| S001 | 2 | 90 | 76 | 3/3 | 0 |
| S001 | 3 | 84 | 73 | 2/3 | 1 |
| S001 | 4 | 78 | 68 | 2/3 | 2 |

This creates a temporal sequence that can be analyzed by deep-learning models.

---

 ## 7.2 Data Preprocessing

 The data-processing pipeline will perform:

 - Missing-value handling
- Duplicate removal
- Outlier checking
- Feature normalization
- Weekly aggregation
- Time-series window creation
- Train/validation/test splitting

 Example features:

```
attendance_7_day
attendance_14_day
subject_attendance
internal_mark
assignment_completion
submission_delay
consecutive_absences
attendance_trend
marks_trend
```

---

 # 8\. LSTM Autoencoder for Anomaly Detection

 An **LSTM Autoencoder** will learn normal student behavior from historical time-series data.

 The model contains:

```
Input Sequence
      ↓
LSTM Encoder
      ↓
Latent Representation
      ↓
LSTM Decoder
      ↓
Reconstructed Sequence
      ↓
Reconstruction Error
```

 The reconstruction error can be calculated using Mean Squared Error:

 $$
MSE = \frac{1}{N}\sum_{i=1}^{N}(x_i-\hat{x_i})^2
$$

 If the reconstruction error becomes significantly higher than the learned normal range, the system marks the sequence as an **anomaly**.

 Possible anomalies include:

 - Sudden attendance decline
- Repeated consecutive absences
- Sudden academic-performance decline
- Increasing assignment delays
- Unusual change in student behavior

---

 # 9\. GRU-Based Risk Prediction

 A **GRU model** will be used to predict the student's future academic trajectory.

 The model receives historical weekly information:

```
Week 1 → Week 2 → Week 3 → Week 4 → ...
```

 and predicts future values such as:

 - Expected final attendance
- Expected academic performance
- Risk of falling below the required attendance
- Academic-risk probability

 Example:

```
Current Attendance       : 78%
Attendance Trend         : Decreasing
Internal Mark Trend      : Decreasing
Consecutive Absences     : 3

              ↓

       GRU Prediction

              ↓

Projected Attendance     : 69%
Academic Risk            : HIGH
```

 The prediction is intended to support **early intervention**, not to make irreversible decisions automatically.

---

 # 10\. Risk Classification

 The prediction and anomaly scores will be combined into a risk-assessment layer.

 | Risk Level | Example Condition | Action |
| --- | --- | --- |
| 🟢 Low | Stable attendance and performance | Continue monitoring |
| 🟡 Medium | Negative trend detected | Advisor intervention |
| 🔴 Critical | Strong anomaly + predicted serious academic risk | Immediate faculty/advisor alert |

 The exact thresholds will be determined experimentally using validation data rather than assuming that a particular threshold will always be optimal.

---

 # 11\. Four-Member Team Division

 The project can be divided into **four major work packages**.

 | Member | Role | Responsibilities | Main Deliverables |
| --- | --- | --- | --- |
| **Member 1** | **Team Lead & Data Engineer** | Project architecture, dataset creation, preprocessing, feature engineering, GitHub management | Dataset, preprocessing pipeline, system architecture |
| **Member 2** | **Anomaly Detection Engineer** | LSTM Autoencoder, anomaly scoring, threshold selection, visualization | LSTM model, anomaly detection module |
| **Member 3** | **Prediction & Risk Engineer** | GRU forecasting, academic-risk prediction, risk classification | GRU model, risk prediction module |
| **Member 4** | **Backend, Integration & Evaluation Engineer** | API, alert system, model integration, testing, performance evaluation, documentation | FastAPI service, integration, test reports |

---

 ## Member 1 – Team Lead & Data Engineering

 ### Responsibilities

 - Understand overall system requirements.
- Design the system architecture.
- Create synthetic/anonymized student datasets.
- Perform data cleaning.
- Handle missing values and outliers.
- Perform exploratory data analysis.
- Create temporal features.
- Prepare training, validation, and testing datasets.
- Maintain the GitHub repository.
- Coordinate integration between all members.

 ### Deliverables

```
data/
├── raw/
├── processed/
└── synthetic/

src/
└── data_pipeline.py

notebooks/
└── 01_data_analysis.ipynb
```

---

 ## Member 2 – LSTM Anomaly Detection

 ### Responsibilities

 - Study LSTM and Autoencoder architecture.
- Develop the LSTM Autoencoder.
- Train the model using normal academic behavior.
- Calculate reconstruction error.
- Determine anomaly thresholds.
- Identify abnormal student patterns.
- Generate anomaly visualizations.
- Tune the model.

 ### Deliverables

```
src/models/
└── autoencoder.py

notebooks/
└── 02_lstm_autoencoder.ipynb
```

 Example output:

```
Student ID: S023

Normal Reconstruction Error: 0.08
Current Reconstruction Error: 0.71

Anomaly Status: DETECTED
Anomaly Type: Attendance/Performance Drift
```

---

 ## Member 3 – GRU Prediction & Risk Analysis

 ### Responsibilities

 - Develop the GRU forecasting model.
- Prepare sequential input data.
- Predict future attendance/performance.
- Calculate academic-risk probability.
- Develop the risk-classification logic.
- Compare different forecasting models if required.
- Evaluate prediction accuracy.

 ### Deliverables

```
src/models/
└── trajectory_gru.py

src/
└── risk_engine.py

notebooks/
└── 03_gru_prediction.ipynb
```

 Example:

```
Current Attendance       : 77.4%
Predicted Final          : 70.2%
Risk Probability         : 0.87

Risk Level               : CRITICAL
```

---

 ## Member 4 – Backend, Integration & Evaluation

 ### Responsibilities

 - Develop the FastAPI backend.
- Connect the trained models to the API.
- Create Pydantic request/response schemas.
- Develop alert-generation logic.
- Integrate with the Chatbot/Academic modules.
- Perform unit and integration testing.
- Measure model inference time.
- Prepare API documentation.
- Prepare final system demonstration.

 ### Deliverables

```
src/api/
├── main.py
└── schemas.py

tests/
├── test_api.py
└── test_models.py
```

 Example API flow:

```
Student Data
     ↓
POST /analyze
     ↓
Data Processing
     ↓
LSTM Anomaly Detection
     ↓
GRU Risk Prediction
     ↓
Risk Engine
     ↓
JSON Response
```

---

 # 12\. Inter-Module API

 The ADM-EWS module can communicate with other modules through a REST API.

 ### Example Request

```
{
  "student_id": "STU001",
  "attendance": 77.5,
  "internal_mark": 62,
  "consecutive_absences": 3,
  "assignment_delay": 2
}
```

 ### Example Response

```
{
  "student_id": "STU001",
  "anomaly_detected": true,
  "anomaly_score": 0.84,
  "predicted_attendance": 69.8,
  "risk_probability": 0.89,
  "risk_level": "CRITICAL",
  "recommended_action": "ADVISOR_INTERVENTION"
}
```

 The API can later be connected to the **student chatbot, faculty dashboard, attendance system, or parent-notification module**.

---

 # 13\. Technology Stack

 ### Programming

 - Python 3.10+
- Pandas
- NumPy
- SciPy
- Scikit-learn

 ### Deep Learning

 - PyTorch or TensorFlow
- LSTM
- GRU

 ### Backend

 - FastAPI
- Pydantic
- Uvicorn

 ### Development

 - Google Colab
- GitHub
- Jupyter Notebook

 ### Visualization

 - Matplotlib
- Seaborn
- Plotly (optional)

---

 # 14\. GitHub Repository Structure

 A simplified structure suitable for a four-member team:

```
ai-campus-disaster-management/
│
├── data/
│   ├── raw/
│   └── processed/
│
├── notebooks/
│   ├── 01_data_analysis.ipynb
│   ├── 02_lstm_anomaly.ipynb
│   └── 03_gru_prediction.ipynb
│
├── src/
│   ├── data_pipeline.py
│   ├── risk_engine.py
│   ├── discrepancy_filter.py
│   │
│   ├── models/
│   │   ├── autoencoder.py
│   │   └── trajectory_gru.py
│   │
│   └── api/
│       ├── main.py
│       └── schemas.py
│
├── tests/
│   ├── test_models.py
│   └── test_api.py
│
├── requirements.txt
├── README.md
└── .gitignore
```

---

 # 15\. Development Timeline

 For a **12-week project**, the work can be divided as follows:

 | Week | Activity | Responsible Members |
| --- | --- | --- |
| 1 | Requirement analysis & system design | All |
| 2 | Dataset creation & GitHub setup | M1 |
| 3 | Data preprocessing & EDA | M1 |
| 4 | Feature engineering & time-series preparation | M1 + M2/M3 |
| 5 | LSTM Autoencoder development | M2 |
| 6 | LSTM training & anomaly analysis | M2 |
| 7 | GRU model development | M3 |
| 8 | GRU training & risk prediction | M3 |
| 9 | Risk engine & model integration | M3 + M4 |
| 10 | FastAPI & alert system | M4 |
| 11 | Testing & performance evaluation | M4 + All |
| 12 | Final integration, report & presentation | All |

---

 # 16\. Evaluation Metrics

 ### Anomaly Detection

 The LSTM Autoencoder will be evaluated using:

 - Precision
- Recall
- F1-score
- ROC-AUC
- Reconstruction-error analysis

 ### Prediction

 The GRU model can be evaluated using:

 - MAE
- RMSE
- MAPE
- R² score

 ### System Performance

 The overall system will additionally measure:

 - API response time
- Model inference time
- End-to-end processing time
- Error rate

 Rather than guaranteeing a particular accuracy before experiments are conducted, the project can define **target benchmarks** and report the actual achieved results.

---

 # 17\. Expected Outcome

 At the end of the project, the team will have a working prototype capable of:

```
Student Academic Data
        ↓
Data Preprocessing
        ↓
Behavior Analysis
        ↓
LSTM Anomaly Detection
        ↓
GRU Future Prediction
        ↓
Risk Assessment
        ↓
Early Warning
        ↓
Faculty / Advisor / Chatbot
```

 The system should be able to identify students whose academic behavior is changing abnormally and provide an **early warning before the situation becomes critical**.

---

 # 18\. Advantages

 - Predictive rather than purely reactive monitoring.
- Detects behavioral changes over time.
- Combines multiple academic indicators.
- Supports early faculty intervention.
- Can integrate with existing campus systems.
- Can initially operate using synthetic/anonymized data.
- Modular architecture allows future expansion.
- Can be deployed as a REST API.

---

 # 19\. Future Enhancements

 The proposed system can later be extended with:

 - Computer-vision attendance integration.
- RFID attendance integration.
- Real-time classroom data.
- Student chatbot integration.
- Parent notification system.
- Faculty dashboards.
- Explainable AI for risk predictions.
- Personalized intervention recommendations.
- Transformer-based time-series models.
- Federated/privacy-preserving learning for sensitive student data.

---

 # 20\. Conclusion

 The **Academic Disaster Management & Early Warning System (ADM-EWS)** provides an intelligent approach to identifying and managing academic risks. By combining **time-series preprocessing, LSTM-based anomaly detection, GRU-based prediction, and automated risk assessment**, the system can move academic monitoring from a reactive model to an early-warning model.

 The four-member division ensures that the project is manageable while giving each member a clearly identifiable technical contribution:

 - **Member 1 → Data \+ Architecture**
- **Member 2 → LSTM Anomaly Detection**
- **Member 3 → GRU Prediction + Risk Engine**
- **Member 4 → API \+ Integration + Testing**

 This division also makes the project easier to demonstrate during the **project review/viva**, because each member can clearly explain and demonstrate an independent component while showing how all four components form one complete ADM-EWS system.

┌─────────────────────────┐
                    │ Object & Face Recognition│
                    │         Team             │
                    └────────────┬────────────┘
                                 │
                     student_id + image
                                 │
                                 ▼
                    ┌─────────────────────────┐
                    │     ADM-EWS TEAM        │
                    │                         │
                    │ Image/Behavior Analysis │
                    │ Sleep Detection         │
                    │ Mobile Usage Detection │
                    │ Academic Risk Analysis │
                    └────────────┬────────────┘
                                 │
              ┌──────────────────┴──────────────────┐
              │                                     │
              ▼                                     ▼
       Behavioral Alert                       Academic Risk
       Mobile / Sleeping                     Attendance / Marks
              │                                     │
              └──────────────────┬──────────────────┘
                                 ▼
                    ┌─────────────────────────┐
                    │     Risk / Alert        │
                    │        Engine           │
                    └────────────┬────────────┘
                                 │
                    ┌────────────┴────────────┐
                    ▼                         ▼
          Academic Evaluation Team      AI Engineering
                                        Frontend/Dashboard
"""

# Install required libraries
!pip install pandas scikit-learn matplotlib seaborn -q

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# Upload your JSON file in Google Colab
from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Load JSON dataset
raw_data_bytes = uploaded[filename]

# Decode bytes to string and remove any leading/trailing whitespace
raw_data_string = raw_data_bytes.decode('utf-8').strip()

# Find the first valid JSON start character ('{' or '[')
start_idx = -1
for i, char in enumerate(raw_data_string):
    if char == '{' or char == '[':
        start_idx = i
        break

if start_idx == -1:
    raise ValueError("Could not find a valid JSON start character ('{' or '[') in the uploaded file content.")

# Find the last valid JSON end character ('}' or ']')
end_idx = -1
for i in range(len(raw_data_string) - 1, -1, -1):
    char = raw_data_string[i]
    if char == '}' or char == ']':
        end_idx = i
        break

if end_idx == -1 or end_idx < start_idx:
    raise ValueError("Could not find a valid JSON end character ('}' or ']') corresponding to the start in the uploaded file content.")

# Extract the most likely JSON substring
json_string_to_parse = raw_data_string[start_idx : end_idx + 1]

# Further clean the extracted JSON string if it starts with '{' or '['
# by removing any non-whitespace characters that are not a quote immediately after the opening character.
if json_string_to_parse.startswith('{'):
    # Remove leading whitespace and newlines after '{' until a non-space/non-newline character is encountered
    idx = 1 # Start checking after '{'
    while idx < len(json_string_to_parse) and json_string_to_parse[idx].isspace():
        idx += 1
    if idx > 1: # If whitespace was found after '{'
        json_string_to_parse = '{' + json_string_to_parse[idx:]
elif json_string_to_parse.startswith('['):
    # Remove leading whitespace and newlines after '[' until a non-space/non-newline character is encountered
    idx = 1 # Start checking after '['
    while idx < len(json_string_to_parse) and json_string_to_parse[idx].isspace():
        idx += 1
    if idx > 1: # If whitespace was found after '['
        json_string_to_parse = '[' + json_string_to_parse[idx:]

# Now, attempt to load this cleaned substring
try:
    data = json.loads(json_string_to_parse)
except json.JSONDecodeError as e:
    # If there's still a JSONDecodeError, provide more context
    raise ValueError(f"Failed to decode JSON from file '{filename}': {e}.\nAttempted to parse this string (first 200 chars):\n'{json_string_to_parse[:200]}'...") from e

# Create a dictionary for quick student information lookup
students = {
    student["student_id"]: student
    for student in data["students"]
}

# Extract performance data
records = []

for student in data["performance_tracker"]:

    student_id = student["student_id"]

    record = {
        "student_id": student_id,
        "name": students.get(student_id, {}).get("name", "Unknown"),
        "department": students.get(student_id, {}).get("department", "Unknown"),
        "overall_attendance": student["overall_attendance_percentage"],
        "overall_average": student["overall_average_score"]
    }

    # Semester-wise features
    semesters = student.get("semesters", [])

    for sem in semesters:
        sem_no = sem["semester"]

        record[f"sem{sem_no}_attendance"] = sem["attendance_percentage"]

        scores = []

        for subject in sem.get("subjects", []):
            if "total_score" in subject:
                scores.append(subject["total_score"])

        if scores:
            record[f"sem{sem_no}_average"] = np.mean(scores)

    records.append(record)

# Convert into DataFrame
df = pd.DataFrame(records)

print("Dataset:")
display(df.head())

# Select numerical features for anomaly detection
features = [
    "overall_attendance",
    "overall_average"
]

# Add semester features automatically
for column in df.columns:
    if "attendance" in column or "average" in column:
        if column not in features:
            features.append(column)

X = df[features].fillna(df[features].mean())

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Isolation Forest model
model = IsolationForest(
    contamination=0.10,
    random_state=42
)

# Predict anomalies
df["anomaly"] = model.fit_predict(X_scaled)

# Convert result into understandable labels
df["status"] = df["anomaly"].map({
    1: "Normal",
    -1: "Anomaly"
})

# Anomaly score
df["anomaly_score"] = model.decision_function(X_scaled)

# Display results in JSON format
print("\n--- Anomaly Detection Results (JSON) ---")
results_df_json = df[
    [
        "student_id",
        "name",
        "department",
        "overall_attendance",
        "overall_average",
        "status",
        "anomaly_score"
    ]
].sort_values("anomaly_score").to_json(orient="records", indent=2)
print(results_df_json)

# Display only anomalous students in JSON format
anomalies = df[df["status"] == "Anomaly"]

print("\n--- Detected Anomalies (JSON) ---")
anomalies_json = anomalies[
    [
        "student_id",
        "name",
        "department",
        "overall_attendance",
        "overall_average",
        "anomaly_score"
    ]
].to_json(orient="records", indent=2)
print(anomalies_json)

# Plot attendance vs average score
plt.figure(figsize=(9, 6))

normal = df[df["status"] == "Normal"]
anomaly = df[df["status"] == "Anomaly"]

plt.scatter(
    normal["overall_attendance"],
    normal["overall_average"],
    label="Normal"
)

plt.scatter(
    anomaly["overall_attendance"],
    anomaly["overall_average"],
    label="Anomaly",
    marker="x",
    s=100
)

plt.xlabel("Overall Attendance (%)")
plt.ylabel("Overall Average Score")
plt.title("Student Anomaly Detection")
plt.legend()
plt.grid(True)
plt.show()

# Save results
df.to_csv("student_anomaly_results.csv", index=False)

print("Results saved as student_anomaly_results.csv")